# Generated by Django 5.0.4 on 2024-04-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoThreads_app', '0004_orders_created_at_orders_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created_at', '-modified_at']},
        ),
    ]
