# Generated by Django 5.0.4 on 2024-04-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoThreads_app', '0005_alter_orders_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
