# Generated by Django 5.0.4 on 2024-04-26 20:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoThreads_app', '0006_alter_orders_created_at_alter_orders_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 4, 26, 20, 4, 51, 309434, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
